name: Android CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Install Tree
      run: sudo apt-get install tree
     
    
    - name: Listing
      run: tree /home/runner/work/ScreenPortrait/ScreenPortrait/app/build/outputs/apk/debug/
    - name: Listing outputs
      run: ls /home/runner/work/ScreenPortrait/ScreenPortrait/app/build/outputs/apk/debug/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: /home/runner/work/ScreenPortrait/ScreenPortrait/app/build/outputs/apk/debug/
     
        name: app-debug.apk

        














